#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
build_dir="${script_dir}/build"
output_dir="${script_dir}/output"

find_tool() {
  command -v "$1" 2>/dev/null || true
}

llvm_config="${LLVM_CONFIG:-$(find_tool llvm-config)}"
cmake_bin="${CMAKE:-$(find_tool cmake)}"
ninja_bin="${NINJA:-$(find_tool ninja)}"
cmake_generator="${CMAKE_GENERATOR:-}"
for tool in "${llvm_config}" "${cmake_bin}"; do
  if [[ -z "${tool}" || ! -x "${tool}" ]]; then
    printf 'missing required tool: %s\n' "${tool:-<unset>}" >&2
    exit 1
  fi
done
if [[ -z "${cmake_generator}" ]]; then
  if [[ -n "${ninja_bin}" && -x "${ninja_bin}" ]]; then
    cmake_generator="Ninja"
  else
    cmake_generator="Unix Makefiles"
  fi
fi
if [[ "${cmake_generator}" == "Ninja" && ( -z "${ninja_bin}" || ! -x "${ninja_bin}" ) ]]; then
  printf 'CMAKE_GENERATOR=Ninja requires ninja; install it or use Unix Makefiles.\n' >&2
  exit 1
fi
if [[ "${cmake_generator}" == "Unix Makefiles" && -z "$(find_tool make)" ]]; then
  printf 'Unix Makefiles requires make; install make or ninja.\n' >&2
  exit 1
fi

llvm_dir="$("${llvm_config}" --cmakedir)"
llvm_bindir="$("${llvm_config}" --bindir)"
plugin_cc="${PLUGIN_CC:-${llvm_bindir}/clang}"
plugin_cxx="${PLUGIN_CXX:-${llvm_bindir}/clang++}"
llvm_clang="${LLVM_CLANG:-${llvm_bindir}/clang}"
kernel_ir="${STENCIL_KERNEL_IR:-${repo_root}/01_llvm_ir_analysis/output/stencil_all_sme.kernels.ll}"
require_recognized="${STENCIL_REQUIRE_RECOGNIZED:-1}"

for tool in "${plugin_cc}" "${plugin_cxx}" "${llvm_clang}"; do
  if [[ ! -x "${tool}" ]]; then
    printf 'missing LLVM compiler: %s\n' "${tool}" >&2
    exit 1
  fi
done
if [[ ! -f "${kernel_ir}" ]]; then
  printf 'missing kernel-only IR: %s\n' "${kernel_ir}" >&2
  printf 'run 01_llvm_ir_analysis/generate_and_check.sh first.\n' >&2
  exit 1
fi

mkdir -p "${build_dir}" "${output_dir}"
cmake_args=(
  -S "${script_dir}" \
  -B "${build_dir}" \
  -G "${cmake_generator}" \
  -DLLVM_DIR:PATH="${llvm_dir}" \
  -DCMAKE_C_COMPILER="${plugin_cc}" \
  -DCMAKE_CXX_COMPILER="${plugin_cxx}" \
  -DCMAKE_BUILD_TYPE=Release
)
if [[ "${cmake_generator}" == "Ninja" ]]; then
  cmake_args+=("-DCMAKE_MAKE_PROGRAM=${ninja_bin}")
fi
"${cmake_bin}" "${cmake_args[@]}"
"${cmake_bin}" --build "${build_dir}"

plugin="${build_dir}/StencilPrefetchPass.so"
if [[ ! -f "${plugin}" ]]; then
  plugin="${build_dir}/StencilPrefetchPass.dylib"
fi
if [[ ! -f "${plugin}" ]]; then
  printf 'pass plugin was not produced in %s\n' "${build_dir}" >&2
  exit 1
fi

after_ir="${output_dir}/stencil_kernels.after.ll"
baseline_ir="${build_dir}/stencil_kernels.baseline.ll"
baseline_assembly="${output_dir}/stencil_kernels.baseline.s"
prefetch_assembly="${output_dir}/stencil_kernels.s"
pass_log="${output_dir}/pass_run.log"
idempotent_ir="${build_dir}/stencil_kernels.idempotent.ll"
idempotency_log="${output_dir}/idempotency_run.log"
budget_ir="${build_dir}/stencil_kernels.no-prefetch.ll"
budget_log="${output_dir}/budget_reject_run.log"
negative_ir="${script_dir}/tests/non_stencil.ll"
negative_after_ir="${build_dir}/non_stencil.after.ll"
negative_log="${output_dir}/negative_run.log"
report="${output_dir}/plugin_test_report.md"
recognition_report="${output_dir}/stencil_recognition_report.md"
decision_report="${output_dir}/stencil_prefetch_decision_report.md"

# The input is already a kernel-only module generated by step 1. No textual
# LLVM-version rewrite is needed when the same LLVM installation owns both
# clang and the pass plugin.
"${llvm_clang}" \
  -x ir -O1 -S -emit-llvm -Wno-override-module \
  -fpass-plugin="${plugin}" \
  "${kernel_ir}" \
  -o "${after_ir}" \
  2> "${pass_log}"

recognized_count="$(grep -c '^StencilAnalysis:' "${pass_log}" || true)"
decision_count="$(grep -c '^StencilDecision:' "${pass_log}" || true)"
enabled_count="$(grep '^StencilDecision:' "${pass_log}" | grep -c 'enable=yes' || true)"
prefetch_count="$(grep -c 'call void @llvm.aarch64.prefetch' "${after_ir}" || true)"
if [[ "${require_recognized}" == "1" && "${recognized_count}" -eq 0 ]]; then
  printf 'no extracted function matches the current 2D5P/3D7P pass model\n' >&2
  printf 'set STENCIL_REQUIRE_RECOGNIZED=0 to inspect extraction only.\n' >&2
  exit 1
fi
if [[ "${prefetch_count}" -ne "${enabled_count}" ]]; then
  printf 'IR prefetch count (%s) does not match enabled decisions (%s)\n' \
    "${prefetch_count}" "${enabled_count}" >&2
  exit 1
fi

"${llvm_clang}" \
  -x ir -O1 -S -emit-llvm -Wno-override-module \
  "${kernel_ir}" \
  -o "${baseline_ir}"
"${llvm_clang}" \
  -x ir -O1 -S -Wno-override-module \
  "${baseline_ir}" \
  -o "${baseline_assembly}"
"${llvm_clang}" \
  -x ir -O1 -S -Wno-override-module \
  "${after_ir}" \
  -o "${prefetch_assembly}"

if grep -Eq '^[[:space:]]*prf(m|um)[[:space:]]' "${baseline_assembly}"; then
  printf 'kernel-only baseline unexpectedly contains software prefetch\n' >&2
  exit 1
fi
assembly_prefetch_count="$(grep -Ec '^[[:space:]]*prf(m|um)[[:space:]]' "${prefetch_assembly}" || true)"
if [[ "${assembly_prefetch_count}" -ne "${prefetch_count}" ]]; then
  printf 'assembly PRFM count (%s) does not match IR prefetch count (%s)\n' \
    "${assembly_prefetch_count}" "${prefetch_count}" >&2
  exit 1
fi

# The pass must be idempotent for every already-prefetched recognized kernel.
"${llvm_clang}" \
  -x ir -O1 -S -emit-llvm -Wno-override-module \
  -fpass-plugin="${plugin}" \
  "${after_ir}" \
  -o "${idempotent_ir}" \
  2> "${idempotency_log}"
idempotent_count="$(grep -c 'call void @llvm.aarch64.prefetch' "${idempotent_ir}" || true)"
if [[ "${idempotent_count}" -ne "${prefetch_count}" ]]; then
  printf 'idempotency changed the prefetch count\n' >&2
  exit 1
fi

# A zero stream budget preserves recognition but forbids all insertions.
SME_PREFETCH_MAX_STREAMS=0 "${llvm_clang}" \
  -x ir -O1 -S -emit-llvm -Wno-override-module \
  -fpass-plugin="${plugin}" \
  "${kernel_ir}" \
  -o "${budget_ir}" \
  2> "${budget_log}"
if grep -q 'call void @llvm.aarch64.prefetch' "${budget_ir}"; then
  printf 'zero stream budget unexpectedly inserted a prefetch\n' >&2
  exit 1
fi

# Non-stencil IR is a separate fixture. It must remain untouched even though
# the pass no longer relies on a function-name prefix.
"${llvm_clang}" \
  -x ir -O1 -S -emit-llvm -Wno-override-module \
  -fpass-plugin="${plugin}" \
  "${negative_ir}" \
  -o "${negative_after_ir}" \
  2> "${negative_log}"
if grep -q 'call void @llvm.aarch64.prefetch' "${negative_after_ir}" || \
   grep -q '^StencilDecision:' "${negative_log}"; then
  printf 'non-stencil fixture received a prefetch decision\n' >&2
  exit 1
fi

{
  printf '# 步骤 2-4 插件验证报告\n\n'
  printf -- '- 输入 kernel IR：`%s`\n' "${kernel_ir}"
  printf -- '- 插件：`%s`\n' "${plugin}"
  printf -- '- LLVM：`%s`\n' "$("${llvm_config}" --version)"
  printf -- '- 提取函数数：`%s`\n' "$(grep -c '^define ' "${kernel_ir}")"
  printf -- '- 已识别 2D5P/3D7P 函数数：`%s`\n' "${recognized_count}"
  printf -- '- 预取决策数：`%s`，启用：`%s`\n' \
    "${decision_count}" "${enabled_count}"
  printf -- '- 插入 intrinsic/汇编 PRFM 数：`%s / %s`\n' \
    "${prefetch_count}" "${assembly_prefetch_count}"
  printf -- '- test/main：不在 kernel IR 中，不参与 pass 或 kernel 汇编链接\n\n'
  printf '未匹配当前 2D5P/3D7P 结构的提取函数会被安全跳过；为它们增加预取前，'
  printf '需要先扩展 StencilAnalysis 与决策模型。\n'
} > "${report}"

{
  printf '# 步骤 3 Stencil 识别报告\n\n```text\n'
  grep '^StencilAnalysis:' "${pass_log}" || true
  printf '```\n'
} > "${recognition_report}"

{
  printf '# 步骤 4 预取决策报告\n\n```text\n'
  grep '^StencilDecision:' "${pass_log}" || true
  printf '```\n'
} > "${decision_report}"

printf 'Plugin: %s\n' "${plugin}"
printf 'Report: %s\n' "${report}"
printf 'Assembly: %s\n' "${prefetch_assembly}"
